steps:
# Docker build
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/just-amp-373710/quickstart-docker-repo/godot-server:v1', '-f', 'builds/Dockerfile-server', '.' ]
#   id: build

# # Run unit tests inside the docker container
# # - name: 'europe-west1-docker.pkg.dev/just-amp-373710/quickstart-docker-repo/quickstart-image:tag1'
# #   entrypoint: python
# #   args: ["-m", "pytest", "chap2"] 

# # Docker Push
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'europe-west1-docker.pkg.dev/just-amp-373710/quickstart-docker-repo/godot-server:v1']

# Deploy the image in a cloud app engine container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - 'builds/app.yaml'
  - '--image-url=europe-west1-docker.pkg.dev/just-amp-373710/quickstart-docker-repo/godot-server:v1'

images:
- 'europe-west1-docker.pkg.dev/just-amp-373710/quickstart-docker-repo/godot-server:v1'

