# Docker image based on ubuntu 23.10
# Docker image for the base server

FROM ubuntu:23.10

WORKDIR /opt

RUN  apt-get update \
  && apt-get install -y wget \
  && apt-get install -y zip \
  && wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_linux_server.64.zip \
  && unzip Godot_v3.5.1-stable_linux_server.64.zip -d /opt

COPY builds /opt

# Expose the UDP port to contact the server
EXPOSE 10567/udp

# Run the Godot server binary on the exported .pck files in server mode (--server)
ENTRYPOINT ["/opt/Godot_v3.5.1-stable_linux_server.64", "-v", "-d", "--main-pack", "/opt/bomber_linux_export.pck", "--server"]
